apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-console
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 70
    targetPort: 15672
    protocol: TCP
  selector:
    name: rabbitmq

