apiVersion: v1
kind: Service
metadata:
  name: spring-starbucks-worker-service
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 6060
      targetPort: 6060
  selector:
    name: spring-starbucks-worker